import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { homePath, ticketsPath } from "@/paths";
import { Button } from "@/components/ui/button";
import { LucideTickets } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="supports-backdrop-blur:bg-background/60 fixed left-0 right-0 top-0 z-20 bg-background/95 backdrop:blur w-full flex justify-between py-2.5 px-5 border-b">
          <div>
            <Button asChild variant="ghost">
              <Link href={homePath()}>
                <LucideTickets />
                <h1 className="ml-2 text-lg font-semibold">TicketBounty</h1>
              </Link>
            </Button>
          </div>
          <div>
            <Button asChild variant="default">
              <Link href={ticketsPath()}>Tickets</Link>
            </Button>
          </div>
        </nav>
        <main className="min-h-screen flex-1 overflow-y-auto overflow-x-hidden bg-secondary/20 flex flex-col py-24 px-8">
          {children}
        </main>
      </body>
    </html>
  );
}
